// Generated by CoffeeScript 1.8.0
(function() {
  module.exports = {
    find: function(name) {
      return this.registry[name] || (function() {
        throw Error("" + name + " is not registered.");
      })();
    },
    register: function(name, clazz) {
      if (typeof name !== 'string') {
        throw Error("First argument must be the name to register the class under");
      }
      return this.registry[name] = clazz;
    },
    registry: {}
  };

}).call(this);

//# sourceMappingURL=registry.js.map
