// Generated by CoffeeScript 1.8.0
(function() {
  var extend, include;

  extend = function(obj, mixin) {
    var method, name;
    for (name in mixin) {
      method = mixin[name];
      obj[name] = method;
    }
    return obj;
  };

  include = function(klass, mixin) {
    return extend(klass.prototype, mixin);
  };

}).call(this);

//# sourceMappingURL=extend.js.map
